color0 #3e4947
color1 #ffb4ab
color2 #bdfff4
color3 #a9cec7
color4 #f3f0ff
color5 #74d7ca
color6 #a9cec7
color7 #dfe3e1
color8 #879390
color9 #ffb4ab
color10 #bdfff4
color11 #a9cec7
color12 #f3f0ff
color13 #74d7ca
color14 #a9cec7
color15 #dfe3e1

cursor                #dfe3e1
cursor_text_color     #0f1413
background            #0f1413
foreground            #dfe3e1
selection_foreground  #bdc9c6
selection_background  #3e4947
active_border_color   #bdfff4
inactive_border_color #3e4947
url_color             #bdfff4

active_tab_foreground   #003732
active_tab_background   #bdfff4
inactive_tab_foreground #bdc9c6
inactive_tab_background #3e4947
cursor_trail_color      #bdc9c6
