config_version = 14

[bar.default]
center = [ "media", "clock", "workspaces" ]
end = [ "tray", "notifications", "clipboard", "network", "bluetooth", "volume" ]
margin_ends = 0
position = "bottom"
start = [ "session", "control-center" ]

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@SUNSHINE",
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@DP-1",
    "lockscreen-widget-0000000000000001"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@SUNSHINE"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 477.33334350585938
    output = "SUNSHINE"
    placement_height = 720.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@SUNSHINE".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 540.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

[plugins]
enabled = [ "kenn/keybind-cheatsheet" ]

[shell]
settings_show_advanced = false
settings_window_translucent = true

[theme.templates]
builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "hyprland", "kitty", "qt" ]

[wallpaper.default]
path = "/home/quiet/Pictures/wallpapers/wallhaven-qrpdz7.jpg"

[wallpaper.last]
path = "/home/quiet/Pictures/wallpapers/wallhaven-qrpdz7.jpg"

[wallpaper.monitors.DP-1]
path = "/home/quiet/Pictures/wallpapers/wallhaven-qrpdz7.jpg"

[wallpaper.monitors.DP-2]
path = "/home/quiet/Pictures/wallpapers/wallhaven-qrpdz7.jpg"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.tray]
capsule = true